# Generated by Django 4.2.14 on 2024-07-25 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(default='', upload_to='services/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('description', models.TextField(blank=True, max_length=100000, null=True, verbose_name='description')),
                ('short_description', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servicesimages/')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_images', to='services.services')),
            ],
            options={
                'verbose_name': 'Services Images ',
                'verbose_name_plural': 'Services Images ',
            },
        ),
    ]
