# Generated by Django 4.2.14 on 2024-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_categoryservice_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryservice',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='image',
            field=models.ImageField(blank=True, upload_to='cat_service_img'),
        ),
        migrations.AddField(
            model_name='categoryservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
