# Generated by Django 4.2.14 on 2024-07-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=1000, verbose_name='short description')),
                ('description', models.TextField(max_length=100000, verbose_name='description')),
                ('image_cover', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'About US',
                'verbose_name_plural': 'About US',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
