# Generated by Django 4.2.14 on 2024-07-25 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'NewsLitter',
                'verbose_name_plural': 'NewsLitter',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='setting/')),
                ('phone1', models.CharField(max_length=30)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('fb_link', models.URLField()),
                ('tiktok_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('whatsapp_link', models.URLField()),
                ('address', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this title is display in slider in home page', max_length=150, verbose_name='title')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(help_text='this image is display in slider in home page', upload_to='homeImages/', verbose_name='image')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_image', to='settings.settings', verbose_name='home_image')),
            ],
            options={
                'verbose_name': 'Home Images',
                'verbose_name_plural': 'Home Images',
            },
        ),
    ]
