# Generated by Django 4.2.14 on 2024-07-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='short_description',
        ),
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
