# Generated by Django 4.2.14 on 2024-07-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_productgallary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallary',
            options={'verbose_name_plural': 'Product Gallary'},
        ),
    ]
